name: Convert DOCX to Markdown

on:
  push:
    paths:
      - 'docs/source-docs/**/*.docx'  # Trigger เมื่อมีการอัปโหลด .docx

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert DOCX files to Markdown
        run: |
          mkdir -p docs/dest-docs
          for file in docs/source-docs/*.docx; do
            [ -e "$file" ] || continue
            filename=$(basename "$file" .docx)
            pandoc "$file" -f docx -t markdown -o "docs/dest-docs/$filename.md"
          done

      - name: Commit and push converted files
        run: |
          git config user.name "Thagoon"
          git config user.email "thagoon.work@gmail.com"
          git add docs/dest-docs/*.md
          git commit -m "Auto-convert DOCX to Markdown"
          git push